exammproject/exammapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='exammapp'
urlpatterns = [

    path('',views.fun,name='fun'),
    path('login/',views.login,name='login'),
    path('register/', views.register, name='register'),
    path('movie/<int:id>/', views.details,name='details'),
    path('log/',views.log,name='log'),
    path('deliver/',views.deliver,name='deliver'),
    path('regi/',views.regi,name='regi'),
    path('add/', views.person_create_view, name='add'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('order/', views.order, name='order'),
    path('ajax/load-prize/', views.load_prize, name='ajax_load_prize'),
    path('success/', views.success, name='success'),
]

exammproject/exammproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('exammapp.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exammproject/exammapp/models.py
from django.db import models

# Create your models here.
class Place(models.Model):
    name1 = models.CharField(max_length=250, unique=True)
    desc1 = models.TextField( unique=True)
    image=models.ImageField(upload_to='pic')
class Country(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=124)
    phoneno=models.CharField(max_length=100)
    address=models.TextField()
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name
class Food(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Prize(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    name = models.IntegerField()


class Quantity(models.Model):

    food = models.ForeignKey(Food, on_delete=models.SET_NULL, blank=True, null=True)
    prize = models.ForeignKey(Prize, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField()

exammproject/exammapp/forms.py
from django import forms

from .models import Person, City


class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

exammproject/exammapp/views.py
from django.contrib import auth, messages
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,redirect
from. models import Place
from django.contrib.auth.models import User
from .forms import PersonCreationForm
from .models import Person, City
from .form import PersonCreation
from .models import Quantity, Prize

# Create your views here.
def fun(request):
    return render(request,"category.html")


def details(request,id):

    obj=Place.objects.get(id=id)
    return render(request,"details.html",{'obj':obj})
def regi(request):




    if request.method == 'POST':


        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        con = request.POST['con']
        if password == con:


            user=User.objects.create_user(username=username, password=password, email=email)
            user.save()
            return redirect('exammapp:deliver')
        else:
            messages.info(request,"pwd and confirm pwd are not same")





    return render(request,"regi.html")






def register(request):




    if request.method == 'POST':


        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        con = request.POST['con']
        if password==con:


             user=User.objects.create_user(username=username, password=password, email=email)
             user.save()
             return redirect('/')
        else:
            messages.info(request,"password nd confirm pwd are not same")






    return render(request,"register.html")
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)

            return redirect('/')
        else:
            return redirect('exammapp:login')

    return render(request,"login.html")
def log(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('exammapp:deliver')
        else:
            return redirect('exammapp:log')
    return render(request,"log.html")
def deliver(request):
    return render(request,"delivery.html")
def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('exammapp:order')
    return render(request, 'home.html', {'form': form})
def load_cities(request):
    country_id = request.GET.get('country_id')
    cities = City.objects.filter(country_id=country_id)

    return JsonResponse(list(cities.values('id', 'name')), safe=False)


def order(request):
    form = PersonCreation()
    if request.method == 'POST':
        form = PersonCreation(request.POST)
        if form.is_valid():


            form.save()

            return redirect('exammapp:success')





    return render(request, 'homee.html', {'form': form})
def load_prize(request):
    food_id = request.GET.get('food_id')
    prize = Prize.objects.filter(food_id=food_id)

    return JsonResponse(list(prize.values('id', 'name')), safe=False)
def success(request):

    return render(request,"success.html")

exammproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
      <link rel="stylesheet" href="{% static 'custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Pacifico&display=swap" rel="stylesheet">


     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}

{% block content %}
{% endblock %}
</div>
<br>
<br>
<br>
{% include 'footer.html' %}
</body>
</html>

exammproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.desc }}
{% else %}}
<h3> WELCOME PRODUCT</h3>
{% endif %}
{% endblock %}




<h3> SEE OUR COLLECTIONS</h3>


{% block  content %}
{% if category %}
<div>
    <div>
        </p><a href="">ALL PRODUCT</a>
    </div>
</div>
{% endif %}

<div>
    <img src="{% static 'img/food.jpg' %}" alt="our pdt" width="1300px;" height="350px;"></div>
<br>
<br>
<div align="center">

   <a class="btn btn-success"   href="{% url 'exammapp:log' %}">Food Ordering</a></div>



    <div>
        {% for i in product %}
        <div style="text-align:center;">
            <a href="{{i.get_url}}"><img src="{{i.imgg.url}}" alt="hello" width="100px;" height="100px;"></a>
            <br>
            {{i.price}}<br>
            <h3>{{i.name}}</h3>
        </div>

        {% endfor %}

        </div>

    <br>


{% endblock %}

exammproject/templates/city.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

exammproject/templates/cityy.html
<option value="">---------</option>
{% for city in prize %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

exammproject/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<img src="{{obj.image.url}}" alt="" width="1200" height="300">
<br>
<br>
{{obj.desc1}}

{% endblock %}

exammproject/templates/footer.html
<br>
<br>

<div style="background-color:aqua;">
    <p style="text-align:center;font-size:20px"> ABC PVT LTD .All right reserved.</p>
</div>

exammproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h3 align="center"><u>Person Form</u></h3>
<br>

<form align="center" method="post" id="personForm" data-cities-url="{% url 'exammapp:ajax_load_cities' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <div align="center">

   <a class="btn btn-success"   href="{% url 'exammapp:order' %}">SUBMIT</a></div>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
   $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                  // replace the contents of the city input with the data that came from the server


                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);


            }
        });

    });
</script>

{% endblock %}

exammproject/templates/homee.html
{% extends 'base.html' %}
{% block content %}
<h3 align="center"><u>FOOD DETAILS</u></h3>
<br>
<br>

<form method="post"  align=center id="personForm" data-prize-url="{% url 'exammapp:ajax_load_prize' %}" >
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <br>
    <div align="center">

   <a class="btn btn-success"   href="{% url 'exammapp:success' %}">SUBMIT</a></div>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
   $("#id_food").change(function () {
        const url = $("#personForm").attr("data-prize-url");  // get the url of the `load_cities` view
        const foodId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'food_id': foodId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                  // replace the contents of the city input with the data that came from the server


                let html_data = '<option value="">---------</option>';
                data.forEach(function (prize) {
                    html_data += `<option value="${prize.id}">${prize.name}</option>`
                });
                console.log(html_data);
                $("#id_prize").html(html_data);



            }
        });

    });
</script>

{% endblock %}

exammproject/templates/log.html
{% extends 'base.html'%}


<body style="background-color:aqua;">
{% block content %}

<h2 align="center"><u>Login Page</u></h2>
<br>
<br>

<form method="post" action="" align="center" color="aqua">
    {% csrf_token %}

    <input type="text" name="username" placeholder="enter username">
    <br>
    <br>
    <input type="password" name="password" placeholder="enter password">
    <br>
    <br>
     <div align="center">

   <a class="btn btn-success"   href="{% url 'exammapp:deliver' %}">DELIVERY DETAILS</a></div>
    <br><br><br><br>
    <br><h4><b><a href="{% url 'exammapp:regi' %}">REGISTER</b></h4>

    <br>
    <br>
</form>

{% endblock %}
</body>

exammproject/templates/login.html
{% extends 'base.html' %}
{% block content %}
<h4 align="center"><u>Login Page</u></h4>
<br>
<br>
<form method="post" action="" align="center">
    {% csrf_token %}

    <input type="text" name="username" placeholder="enter username">
    <br>
    <br>
    <input type="password" name="password" placeholder="enter password">
    <br>
    <br>
    <input type="submit">
    <br>
    <br>
    {% endblock %}


</form>
</body>
</html>

exammproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'exammapp:fun' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exammapp:login' %}">LOGIN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exammapp:register' %}">REGISTER</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Place
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            {% for cat in link %}
            <li><a class="dropdown-item" href="{% url 'exammapp:details' cat.id %}">{{cat.name1}}</a></li>

            {% endfor %}



          </ul>
        </li>


      </ul>

    </div>
  </div>
</nav>
<br>
<br>

exammproject/templates/regi.html
{% extends 'base.html' %}
{% block content %}
<h3 align="center"><u>Registration Form</u></h3>
<br>
<form method="post" action="" align="center">
    {% csrf_token %}
       <input type="text" name="username" placeholder="enter username"><br>

      <input type="password" name="password" placeholder="enter password">
    <br>
    <input type="password" name="con" placeholder="enter confirm pwd">
    <br>
         <input type="email" name="email" placeholder="enter email">
    <br>
    <br>
    <div align="center">

   <a class="btn btn-success"   href="{% url 'exammapp:deliver' %}">SUBMIT</a></div>
</form>
{% for i in messages %}
{{i}}
{% endfor %}
{% endblock %}

exammproject/templates/register.html
{% extends 'base.html' %}
{% block content %}
<h4  align="center"><u>REGISTRAION FORM</u></h4>
<br>
<br>
<form method="post" action="" align="center">
    {% csrf_token %}
       <input type="text" name="username" placeholder="enter username"><br>

      <input type="password" name="password" placeholder="enter password">
    <br>
    <input type="password" name="con" placeholder="enter confirm pwd">
    <br>
         <input type="email" name="email" placeholder="enter email">
    <br>
    <br>
    <input type="submit">
</form>
{% for i in messages %}
{{i}}
{% endfor %}
{% endblock %}

exammproject/templates/success.html
{% extends 'base.html' %}
<style>
    <body bgcolor:aqua;>
</style>
{% block content %}
<body>
<h3 align="center" ><u>UR ORDER  IS PLACED</u></h3>
<h4 align="center"><u>THANK U</u></h4>
<br>
<br>
<div align="center">

   <a class="btn btn-success"   href="{% url 'exammapp:fun' %}">LOGOUT</a></div>
</body>
{% endblock %}